### ISSUE TITLE
KeyError: "Invalid board option 'upload.protocol'"

### ISSUE THREAD

**Issue by kalon33** [jcaridadhdez/RAK811-tracker#4]
When following wiki instructions under Ubuntu 19.10, I got this error in Platform.io, which prevent any build.

```
nicolas@morgan:~/sources/RAK811-tracker$ pio run
Warning! Ignore unknown configuration option `lib_dir` in section [env:rak811]
Warning! Ignore unknown configuration option `src_dir` in section [env:rak811]
Processing rak811 (platform: ststm32; board: rak811; framework: cmsis)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py", line 138, in cli
    is_test_running,
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py", line 170, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/processor.py", line 80, in process
    result = p.run(build_vars, build_targets, self.silent, self.verbose, self.jobs)
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/managers/platform.py", line 383, in run
    self.configure_default_packages(options, targets)
  File "/home/nicolas/.platformio/platforms/ststm32/platform.py", line 34, in configure_default_packages
    "board")).get("upload.protocol") or ""
  File "/home/nicolas/.platformio/penv/lib/python3.7/site-packages/platformio/managers/platform.py", line 731, in get
    raise KeyError("Invalid board option '%s'" % path)
KeyError: "Invalid board option 'upload.protocol'"
```
An idea how to fix this? I'm not used to Platform.io, so that might be trivial...

**Comment by Ebiroll** [comment]
You can fix the error by adding like this https://github.com/Ebiroll/RAK811_BreakBoard/commit/85dd1a84939d970246b339a6b45ca4cac4825bec
